version: '2'
services:
  demosp:
    container_name: isb-integration-example
    build:
      context: ./
    environment:
      - API_HOST=https://isb-test.op.fi
      - CLIENT_ID=saippuakauppias
      - REDIRECT_URI=http://localhost
      - REDIRECT_URI_EMBEDDED=http://localhost/embedded.php
      - REDIRECT_URI_EMBEDDED2=http://localhost/embedded2.php
      - PRIVATE_KEY_PATH=/var/www/privkey.pem
      - SIGNING_KEY_PATH=/var/www/sp-signing-key.pem
      # This is jwks cache age in seconds (43200 = 12 hours)
      - CACHE_REFRESH_RATE=43200
      # JWKS key cache file location. Do not use /tmp as a place for cache in production environment
      - JWKS_CACHE_FILE=/tmp/isbcache.json
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"